server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/v1/ {
        proxy_pass http://data-service:8080/api/v1/;
    }

    location /planning/ {
        proxy_pass http://planning-engine:8081/planning/;
    }
}
